apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-persistent-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  hostPath:
    path: "/mnt/mongo_data"
